//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//
//  This file was generated by the VIPER Templates,
//  see https://github.com/ViktorChernykh/viper-template
//

import Foundation

final class ___VARIABLE_moduleName___ModuleBuilder: ___VARIABLE_moduleName___Builder {

    static let shared = ___VARIABLE_moduleName___ModuleBuilder()

    private init() {}

    //MARK: ___VARIABLE_moduleName___Builder method
    func build(with viewController: ___VARIABLE_moduleName___ViewController) {
        
        let router = ___VARIABLE_moduleName___Router()
        let presenter = ___VARIABLE_moduleName___Presenter()
        let interactor = ___VARIABLE_moduleName___Interactor()
        
        viewController.presenter = presenter

        presenter.router = router
        presenter.interactor = interactor
        presenter.viewController = viewController

        router.presenter = presenter
        router.viewController = viewController
        
        interactor.presenter = presenter
    }
}

