//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//
//  This file was generated by the VIPER Templates,
//  see https://github.com/ViktorChernykh/viper-template
//

import Foundation
import UIKit

final class ___VARIABLE_moduleName___ViewController: UIViewController, ___VARIABLE_moduleName___ViewControllerBase {

    // MARK: @IBOutlets
    //@IBOutlet weak var nameLabel: UILabel!

    // MARK: Variables
    var selfToASomethingSegueName = "showSomething"
    var presenter: ___VARIABLE_moduleName___ViewOutput?

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)

        setupView()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)

        setupView()
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        
        ___VARIABLE_moduleName___ModuleBuilder.shared.build(with: self)
        setupView()
    }

    // MARK: Do something

    func setupView() {
        presenter?.setupView()
    }

}

// MARK: - Navigation

extension ___VARIABLE_moduleName___ViewController {

    @IBAction func goToOtherView(_ sender: UIButton) {
        presenter?.goToOtherView()
    }
}

// MARK: - ___VARIABLE_moduleName___ViewInput

extension ___VARIABLE_moduleName___ViewController: ___VARIABLE_moduleName___ViewInput {
    
    func setSomething(with title: String) {
        //nameLabel.text = title
    }

}
