//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//
//  This file was generated by the VIPER Templates,
//  see https://github.com/ViktorChernykh/viper-template
//

import Foundation

final class ___VARIABLE_moduleName___Formatter: ___VARIABLE_moduleName___FormatterInOut {
    func doFormat() -> String {
        
        return ""
    }
}
