//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//
//  This file was generated by the VIPER Templates,
//  see https://github.com/ViktorChernykh/viper-template
//

import Foundation

final class ___VARIABLE_moduleName___Interactor: ___VARIABLE_moduleName___InteractorBase, ___VARIABLE_moduleName___InteractorInput {

    // MARK: Properties
    
    weak var presenter: ___VARIABLE_moduleName___InteractorOutput?

    // MARK: - ___VARIABLE_moduleName___InteractorInput methods
    
}
