//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//
//  This file was generated by the VIPER Templates,
//  see https://github.com/ViktorChernykh/viper-template
//

@testable import ___PROJECTNAMEASIDENTIFIER___
import XCTest

class ___VARIABLE_moduleName___PresenterTests: XCTestCase {
    // MARK: Subject under test

    var sut: ___VARIABLE_moduleName___Presenter!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setup___VARIABLE_moduleName___Presenter()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setup___VARIABLE_moduleName___Presenter() {
        sut = ___VARIABLE_moduleName___Presenter()
    }

    // MARK: Test doubles

    class ___VARIABLE_moduleName___DisplayLogicSpy: ___VARIABLE_moduleName___DisplayLogic {
        var displaySomethingCalled = false

        func displaySomething(viewModel: ___VARIABLE_moduleName___.Something.ViewModel) {
            displaySomethingCalled = true
        }
    }

    // MARK: Tests

    func testPresentSomething() {
        // Given
        let spy = ___VARIABLE_moduleName___DisplayLogicSpy()
        sut.viewController = spy
        let response = ___VARIABLE_moduleName___.Something.Response()

        // When
        sut.presentSomething(response: response)

        // Then
        XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
    }
}
