//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//
//  This file was generated by the VIPER Templates,
//  see https://github.com/ViktorChernykh/viper-template
//

@testable import ___PROJECTNAMEASIDENTIFIER___
import XCTest

class ___VARIABLE_moduleName___RouterTests: XCTestCase {
    // MARK: Subject under test

    var sut: ___VARIABLE_moduleName___Router!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setup___VARIABLE_moduleName___Router()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setup___VARIABLE_moduleName___Router() {
        sut = ___VARIABLE_moduleName___Router()
    }

    // MARK: Test doubles

    // MARK: Tests

    func testSomething() {
        // Given

        // When

        // Then
    }
}
