//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//
//  This file was generated by the VIPER Templates,
//  see https://github.com/ViktorChernykh/viper-template
//

import Foundation

final class ___VARIABLE_moduleName___Presenter: ___VARIABLE_moduleName___PresenterBase {

    // MARK: Properties
    
    var moduleData: String?

    weak var viewController: ___VARIABLE_moduleName___ViewInput?
    var interactor: ___VARIABLE_moduleName___InteractorInput?
    var router: ___VARIABLE_moduleName___RouterInput?
    //var formatter: ___VARIABLE_moduleName___FormatterInOut?

}

// MARK: ___VARIABLE_moduleName___ViewOutput methods
extension ___VARIABLE_moduleName___Presenter: ___VARIABLE_moduleName___ViewOutput {
    func setupView() {

    }
    func doSomething() {

    }
    func goToOtherView() {
        router?.routeToSomeWhere()
    }
}

// MARK: ___VARIABLE_moduleName___InteractorOutput methods
extension ___VARIABLE_moduleName___Presenter: ___VARIABLE_moduleName___InteractorOutput {

}

// MARK: ___VARIABLE_moduleName___RouterOutput methods
extension ___VARIABLE_moduleName___Presenter: ___VARIABLE_moduleName___RouterPassData {
    
    func setData(something: String) {
        moduleData = something
    }

}
