//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//
//  This file was generated by the VIPER Templates,
//  see https://github.com/ViktorChernykh/viper-template
//

import Foundation
import UIKit

// MARK: - ViewController

protocol ___VARIABLE_moduleName___ViewControllerBase: class {
    var presenter: ___VARIABLE_moduleName___ViewOutput? { get set }
}

protocol ___VARIABLE_moduleName___ViewInput: class {
    func setSomething(with title: String)
}

// MARK: - Presenter

protocol ___VARIABLE_moduleName___PresenterBase: class {
    var viewController: ___VARIABLE_moduleName___ViewInput? { get set }
    var interactor: ___VARIABLE_moduleName___InteractorInput? { get set }
    var router: ___VARIABLE_moduleName___RouterInput? { get set }
}

protocol ___VARIABLE_moduleName___ViewOutput: class {
    // TODO: Declare presenter methods
    func setupView()
    func doSomething()
    func goToOtherView()
}

protocol ___VARIABLE_moduleName___InteractorOutput: class {
    // TO-DO: Declare interactor output methods
}

protocol ___VARIABLE_moduleName___RouterPassData: class {
    func setData(something: String)
}

// MARK: - Interactor

protocol ___VARIABLE_moduleName___InteractorBase: class {
    var presenter: ___VARIABLE_moduleName___InteractorOutput? { get set }
}

protocol ___VARIABLE_moduleName___InteractorInput: class {
    // TODO: Declare interactor methods
}

// MARK: - Router

protocol ___VARIABLE_moduleName___RouterBase: class {
    var viewController: ___VARIABLE_moduleName___ViewController? { get set }
    var presenter: ___VARIABLE_moduleName___RouterPassData? { get set }
}

protocol ___VARIABLE_moduleName___RouterInput: class {
    func routeToSomeWhere()
}

// MARK: - Builder

protocol ___VARIABLE_moduleName___Builder {
    func build(with:  ___VARIABLE_moduleName___ViewController)
}

protocol ___VARIABLE_moduleName___FormatterInOut: class {
    // TODO: Declare formatter methods
    func doFormat() -> String
}
